### ISSUE TITLE
can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes

### ISSUE THREAD

**Issue by alexjamesbrown** [riezebosch/AzureFunctions.TestHelpers#22]
Trying to use with a ServiceBusEvent trigger, but I get 
> 'ServiceBusEventSubscriber' can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes?

Here's the trigger (starter)

```
        [FunctionName(nameof(ServiceBusEventSubscriber))]
        public async Task Handle(
            [ServiceBusTrigger(
                "%TopicName%",
                "%SubscriptionName%",
                Connection = "ConnectionName")]
            ServiceBusReceivedMessage[] messages,
            [DurableClient] IDurableOrchestrationClient starter)
        {
            foreach (var message in messages)
            {
                var messageJson = Encoding.UTF8.GetString(message.Body);

                await starter
                    .StartNewAsync(nameof(Orchestrator), null, messageJson);
            }
        }
```

I'm setting up the host like this:

    _host = new HostBuilder()
        .ConfigureWebJobs(builder => builder
            .AddServiceBus()
            .AddDurableTask(options => options.HubName = nameof(DurableFunctionsHelper))
            .AddAzureStorageCoreServices()
            .ConfigureServices(services => {}))
        .Build();

And the test like this

        [Fact]
        public async Task WaitFor()
        {
            // Arrange
            var jobs = _host.Jobs;

            // Act
            var serviceBusMessage = GetServiceBusReceivedMessage(JsonConvert.SerializeObject(new TestMessage()));

            await jobs.CallAsync(nameof(ServiceBusEventSubscriber), new Dictionary<string, object>
            {
                ["messages"] = new[] { serviceBusMessage }
            });

But  unfortunately it throws that exception

**Comment by riezebosch** [comment]
I've had success when using a custom type for the message: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp

```csharp
        [FunctionName(nameof(ServiceBusEventSubscriber))]
        public async Task Handle(
            [ServiceBusTrigger(
                "%TopicName%",
                "%SubscriptionName%",
                Connection = "ConnectionName")]
            TestMessage message,
            [DurableClient] IDurableOrchestrationClient starter)
        {
                await starter
                    .StartNewAsync(nameof(Orchestrator), null, message);
            }
        }
```

And calling the function with serialized JSON instead.

```csharp
        await jobs.CallAsync(nameof(ServiceBusEventSubscriber), new Dictionary<string, object>
        {
            ["message"] = JsonConvert.SerializeObject(new TestMessage())
        });
````
