### ISSUE TITLE
TimerTrigger - System.InvalidOperationException : 'TimerFunction' can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes?

### ISSUE THREAD

**Issue by mahgo** [riezebosch/AzureFunctions.TestHelpers#27]
I'm now attempting to get a basic TimerTrigger Azure Function test working, however I'm getting the following issue below. I've based this one off of code in the README as well as in the tests project in the source code. I've looked at the other github issues to try work this one out but have had no luck. What am I missing?
```
Message: 
  System.InvalidOperationException : 'TimerFunction' can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes?

Stack Trace: 
  JobHost.CallAsyncCore(IFunctionDefinition function, Object functionKey, IDictionary`2 arguments, CancellationToken cancellationToken) line 233
  JobHost.CallAsync(String name, IDictionary`2 arguments, CancellationToken cancellationToken) line 225
  TimerFunctionsTests.TimerFunctionTests() line 37
  GenericAdapter`1.GetResult()
  AsyncToSyncAdapter.Await(Func`1 invoke)
  TestMethodCommand.RunTestMethod(TestExecutionContext context)
  TestMethodCommand.Execute(TestExecutionContext context)
  <>c__DisplayClass4_0.<PerformWork>b__0()
  <>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
  ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
  ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  ContextUtils.DoIsolated(ContextCallback callback, Object state)
  ContextUtils.DoIsolated[T](Func`1 func)
  SimpleWorkItem.PerformWork()
```

Here's how my function class looks:
```
using Microsoft.Azure.WebJobs;

namespace AFTests.AzureFunctions.Functions
{
    public class TimerFunctions
    {
        [FunctionName("TimerFunction")]
        public void TimerFunction([TimerTrigger("0 0 1 * * *")]TimerInfo timerInfo)
        {
        }
    }
}
```

Here's how my test class looks:
```
using AzureFunctions.TestHelpers;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Azure.WebJobs.Extensions.Timers;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using NUnit.Framework;

namespace AFTests.AzureFunctions.Tests.Tests
{
    public class TimerFunctionsTests
    {
        [Test]
        public async Task TimerFunctionTests()
        {
            // setup
            using IHost host = new HostBuilder()
                .ConfigureWebJobs(builder => builder
                    .AddDurableTask(options => options.HubName = nameof(TimerFunctionsTests))
                    .AddAzureStorageCoreServices()
                    .UseWebJobsStartup<Startup>())
                .Build();
            await host.StartAsync();

            IJobHost? jobs = host.Services.GetRequiredService<IJobHost>();

            // act
            await jobs.CallAsync("TimerFunction", new Dictionary<string, object>
            {
                ["timerInfo"] = new TimerInfo(new WeeklySchedule(), new ScheduleStatus())
            });

            await jobs.Ready().ThrowIfFailed().Purge();
        }
    }
}
```

**Comment by riezebosch** [comment]
I'm using it like that in [my tests as well]( https://github.com/riezebosch/AzureFunctions.TestHelpers/blob/main/AzureFunctions.TestHelpers.Tests/DurableFunctionsHelpers.cs#L39) and my [host](https://github.com/riezebosch/AzureFunctions.TestHelpers/blob/main/AzureFunctions.TestHelpers.Tests/DurableFunctionsHelpers.cs#L189-L194). 

I've seen differences between NUnit and xUnit where the referenced projects are not automatically loaded with the former. The trick I use to fix that is starting your test with:

```csharp
 _ = typeof(TimerFunction).FullName; // make sure the type is loaded to be resolved as function
```

<s>But that should probably result in a different error.</s>

Last thing I can imagine is that the SDK has evolved and you now need to do the `.AddTimers()` 🤷🏻 

It probably is the NUnit thing.

**Comment by mahgo** [comment]
Hi @riezebosch,

` _ = typeof(TimerFunction).FullName;` didn't change anything for me, but `.AddTimers()` seems to have done the trick, thanks. 

Could having this added cause issues, as per the readme?

I also tried using XUnit instead of NUnit and got the exact same results. 

Also, when trying to run the DurableFunctionsHelper tests in your project, I get the following error for those tests, do you know why that might be?
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: PurgeFunction
---- DurableTask.AzureStorage.Storage.DurableTaskStorageException : 0:The specified resource does not exist.
RequestId:52ebad5d-bd7e-45c5-86c8-4ac31127b5c5
Time:2023-01-10T06:07:10.241Z
```

**Comment by riezebosch** [comment]
> Also, when trying to run the DurableFunctionsHelper tests in your project, I get the following error for those tests, do you know why that might be?

You're probably using Azurite for Storage Account? Technically you don't need to purge there and it seems that the specific operation is not implemented there. I haven't come up with a solution for that yet.

**Comment by mahgo** [comment]
Yeah that's correct, I am using Azurite. What does purge actually do? Are you using the old storage emulator?

Also to confirm, what kind of issues will adding `.AddTimers()` cause for tests (as per the readme)? Will it cause issues with testing?

**Comment by riezebosch** [comment]
Purge cleans up the storage container where the state of durable functions is stored. You don't need that since you can recycle your azurite instance easily. Tip: I use FluentDocker to spin up an azurite container for me during tests.

```
        private readonly IContainerService _azurite = new Builder()
            .UseContainer()
            .UseImage("mcr.microsoft.com/azure-storage/azurite")
            .ExposePort(10000, 10000)
            .ExposePort(10001, 10001)
            .ExposePort(10002, 10002)
            .Build()
            .Start();
```

And [testcontainers](https://github.com/testcontainers/testcontainers-dotnet) also has azurite support built in.
