### ISSUE TITLE
QueueTrigger testing support

### ISSUE THREAD

**Issue by mahgo** [riezebosch/AzureFunctions.TestHelpers#28]
How possible would it be to add support for testing Azure Functions that use QueueTriggers?

**Comment by riezebosch** [comment]
Very much possible. I've had it working with nothing more than `.AddAzureStorage` and make sure you pass in a `string` (=serialized object) for your input message. I've seen in the decompiled code there is a special treatment for input strings that makes this work.

**Comment by riezebosch** [comment]
Feel free when you have this working to add it to the readme!

**Comment by mahgo** [comment]
Thanks! I'll check it out and add it to the readme once I work it out.

**Comment by mahgo** [comment]
Hi @riezebosch,

I've just been trying this out now. When you say `.AddAzureStorage` do you mean `.AddAzureStorageCoreServices` or something else? I can't find `.AddAzureStorage`.

I'm getting this error:
```
System.InvalidOperationException : 'QueueFunction' can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes?
```

Here is my test code:
```
using IHost host = new HostBuilder()
    .ConfigureWebJobs(builder => builder
        .AddAzureStorageCoreServices()
        .UseWebJobsStartup(typeof(TestsStartup), new WebJobsBuilderContext(), NullLoggerFactory.Instance))
    .Build();
await host.StartAsync();

IJobHost? jobs = host.Services.GetRequiredService<IJobHost>();

await jobs.CallAsync("QueueFunction", new Dictionary<string, object>
{
    ["queueItem"] = "test"
});
```

Here is my function code:
```
[FunctionName("QueueFunction")]
public async Task QueueFunction([QueueTrigger("test-queue")] string queueItem)
{
    ...
}
```

**Comment by riezebosch** [comment]
`.AddAzureStorageQueues()`

**Comment by mahgo** [comment]
Thanks @riezebosch. I added a PR for adding this to the readme.
